services:
  web:
    container_name: studynexus-nginx
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    restart: unless-stopped # Automatically restart unless the service is explicitly stopped
    volumes:
      # Mount the 'studynexus-storage-production' volume to '/var/www/storage' inside the container.
      # -----------------------------------------------------------
      # This volume stores persistent data like uploaded files and cache.
      # The ':ro' option mounts it as read-only in the 'web' service because Nginx only needs to read these files.
      # The 'php-fpm' service mounts the same volume without ':ro' to allow write operations.
      # -----------------------------------------------------------
      - studynexus-storage-production:/var/www/storage:ro
      - studynexus-public-assets:/var/www/public/build:ro
    networks:
      - studynexus-production
    ports:
      # Map port 80 inside the container to the port specified by 'NGINX_PORT' on the host machine.
      # -----------------------------------------------------------
      # This allows external access to the Nginx web server running inside the container.
      # For example, if 'NGINX_PORT' is set to '8080', accessing 'http://localhost:8080' will reach the application.
      # -----------------------------------------------------------
      - 80:80
      - 443:443

    depends_on:
      php-fpm:
        condition: service_healthy # Wait for php-fpm health check

  php-fpm:
    # For the php-fpm service, we will create a custom image to install the necessary PHP extensions and setup proper permissions.
    container_name: studynexus-php
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production
    restart: unless-stopped
    volumes:
      - studynexus-public-assets:/var/www/public/build # Mount built public assets to ensure the manifest.json and hashed files match between Nginx and PHP-FPM
      - studynexus-storage-production:/var/www/storage # Mount the storage volume
    env_file:
      - .env
    networks:
      - studynexus-production
    healthcheck:
      test: [ "CMD-SHELL", "php-fpm-healthcheck || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
    # The 'depends_on' attribute with 'condition: service_healthy' ensures that
    # this service will not start until the 'mysql' service passes its health check.
    # This prevents the application from trying to connect to the database before it's ready.
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: studynexus-mysql
    image: mysql:8.4
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-studynexus}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
    volumes:
      - mysql-data-production:/var/lib/mysql
    networks:
      - studynexus-production

    # healthcheck:
    #   test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p${MYSQL_ROOT_PASSWORD:-secret}" ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h mysql -p$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: studynexus-redis
    image: redis:alpine
    restart: unless-stopped # Automatically restart unless the service is explicitly stopped
    networks:
      - studynexus-production
    # Health check for Redis
    # -----------------------------------------------------------
    # Checks if Redis is responding to the 'PING' command.
    # This ensures that the service is not only running but also operational.
    # -----------------------------------------------------------
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8888:80
    environment:
      - PMA_HOST=studynexus-mysql
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    networks:
      - studynexus-production

networks:
  # Attach the service to the 'studynexus' network.
  # -----------------------------------------------------------
  # This custom network allows all services within it to communicate using their service names as hostnames.
  # For example, 'php-fpm' can connect to 'mysql' by using 'mysql' as the hostname.
  # -----------------------------------------------------------
  studynexus-production:


volumes:
  mysql-data-production:
  studynexus-storage-production:
  studynexus-public-assets:
